### PR TITLE
add support for multiple instances of same app in dashboard2

### PR DESCRIPTION
**Pull request by Kariton**
**Description of the change**
currently multiple instances of the same app get mixed into the same panel.
this results in duplicated data like two, ore more times `Queued,  Downloaded, History, Disk Used, Disk Free` in one panel.

i added variables about all instances and "Repeat for" to each app row to mitigate the problem.

**Benefits**
proper support for users with multiple installations of the same app

**Possible drawbacks**
nothing i can think of

**Applicable issues**

- _

**Additional information**

### CODE REVIEW

**Comment by onedr0p** [comment]
Thanks!

**Comment by reefland** [comment]
@Kariton - this update completely broke all my dashboards.  I only have a single instance of each.  If I select "ALL" or select an individual instance, still have no data available now.

image

If I look at the individual stat, and change the `=` to `=~` it starts working for me:
image

If that does not break multi-panel instances, can you update them all.  I don't want to submit a PR that fixes all my single instances but breaks your multi-instance again.  Or if there is a better way to fix this, let me know I'll test that too.

**Comment by Kariton** [comment]
Hey, sorry for my late reply.

Sorry for the inconvenience.
Later this weekend i will find the time to review that and provide a fix.

**Comment by Kariton** [comment]
So i finally got the time to review this and i must admit that i am not sure how i could crew this up...
i _know_ that this is a problem with repeating rows / dashboards....

fix is on the way.

**Pull request merged**
