### PR TITLE
chore: refactor github directory files

### PR DESCRIPTION
**Pull request by onedr0p**
**Description of the change**

Move actions out of workflow dir
Remove ci skip clause

### CODE REVIEW

**Comment by rtrox** [comment]
lgtm!

**Comment by onedr0p** [comment]
I see there are errors in the workflow runs but they shouldn't happen again.

**Comment by rtrox** [comment]
It looks like workflows are failing on subsequent PRs (I merged a dependency update):

[Looking at the docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow), I think they have to be in a subdirectory of `workflows`, or it assumes they're outside our repo (and is therefore looking for a repo version).

I think we can probably fix this by moving them into workflows in a subdirectory (`workflows/subworkflows` or `workflows/actions`)

**Comment by onedr0p** [comment]
It is pretty weird, I checked here first to see if it would work https://github.com/onedr0p/containers/blob/10ffbf2fd17498977a340e879658a0a1ec0c2dcb/.github/workflows/image-rebuild.yaml#L25

**Pull request merged**
