### PR TITLE
Fix Sabnzbd issues and var instance refresh

### LINKED ISSUE #176: Sabnzbd - something wacky with download rate metric
exportarr: `v1.4.0` / sabnzbd: `4.0.1`

@rtrox - For Sabnzb dashboard `Download Rate` I'm using this to drive that panel: `avg(increase(sabnzbd_server_downloaded_bytes[$__rate_interval])) by (server)` with unit `bytes/sec(IEC)`

image

There is no way that test was grabbing at over 8Gib/Sec when the network total for that container was under 100Mib/sec.  Any ideas on what's the proper metric to use for that panel?

### LINKED ISSUE #193: Multi-instance dashboard issues.
Testing multi-instance dashboard fix in #192 which worked mostly except for:

1. `sabnzbd` always returned no instances.  I tracked this down to a misspelling in the instance variable.  instead of  `bd` it is using `db` which is backwards.  Should be `{__name__=~"sabnzbd_.*"}` not `{__name__=~"sabnzdb_.*"}`.

2. All instance variables are set to refresh only on dashboard load only.  If you change the time range using the date picker in the dashboard, the number of instances running during the new time range is not updated.

3. The version number within the dashboard yaml was not bumped.  (it's the 3rd line from the bottom of the file).

I'll submit a PR to address these issues.

### PR DESCRIPTION
**Pull request by reefland**
**Description of the change**

* Fixed sabnzbd variable label spelling mistake
* Instance variables now refresh when range picker is modified
* sabnzbd D/L rates now shown accurately
* Bumped dashboard yaml version

**Applicable issues**

- Fixes #193
- Fixes #176

### CODE REVIEW

**Comment by rtrox** [comment]
Amazing, thanks @reefland!

I think in the future, we should probably add a requirement for a screenshot of dashboards on PRs (to try and prevent this type of breakage)

**Comment by rtrox** [comment]
Oh it has some conflicts -- mind rebasing? Glad to merge once you're done.

**Comment by onedr0p** [comment]
I didn't see this PR before I merged the other one, sorry!

**Comment by onedr0p** [comment]
I reverted the other PR to get this merged.

**Pull request merged**
