### PR TITLE
feat(add): Add indexer statistics to prowlarr collector

### LINKED ISSUE #89: Add statistics for indexers
# Details

**Describe the solution you'd like:**
I would like a solution to compare indexers and check what indexer performs the best

### PR DESCRIPTION
**Pull request by rtrox**
**Description of the change**

This PR adds collection from the /indexers and /indexerstats endpoint for prowlarr, which allows collecting the following metrics:
- **Overall:**
  - `prowlarr_indexer_total`: total number of configured indexers
  - `prowlarr_indexer_enabled_total`: Total number of enabled indexers
- **Tagged by Indexer**:
  - `prowlarr_indexer_average_response_time_ms`: This is unfortunately a Guage instead of a histogram :-/ Prowlarr only exposes average via API.
  - `prowlarr_indexer_queries_total`: Total Queries to this indexer.
  - `prowlarr_indexer_grabs_total`: Total Grabs from this indexer
  - `prowlarr_indexer_rss_queries_total`: Total RSS Queries to this indexer
  - `prowlarr_indexer_auth_queries_total`: Total Auth Queries to this indexer
  - `prowlarr_indexer_failed_queries_total`: Total Failed Queries to this indexer
  - `prowlarr_indexer_failed_grabs_total`: Total Failed Grabs to this indexer
  - `prowlarr_indexer_failed_rss_queries_total`: Total failed RSS queries to this indexer
  - `prowlarr_indexer_failed_auth_queries_total`: Total failed Auth Queries to this indexer
  -  `prowlarr_indexer_vip_expires_in_seconds`: Seconds until VIP expiration for this indexer
- **Tagged by User Agent**:
  -  `prowlarr_user_agent_queries_total` - Total Queries by a given user agent. Typically this will be a list of Apps (Radarr, Sonarr, etc)
  - `prowlarr_user_agent_grabs_total` - Total Grabs by a given user agent.

**Other than `prowlarr_indexer_average_response_time_ms`, all metrics are exposed as Counters, so they can be aggregated with all the normal PromQL tools (`sum()` to get stats for all indexers, `increase()` to measure only a given time period, `rate()`/`irate()` to see rate of increase.**

**Benefits**

This PR gives clear metrics around indexers, as exposed by Prowlarr.

**Possible drawbacks**

Right now, the first /metrics request backfills the cache for all indexers/user agents since the beginning of time. Depending how long a prowlarr instance has been active, and how many requests it's handled, this may take a while (on my instance, 5 seconds,  but I imagine this could be much longer).

There's definitely a tradeoff here: I imagine there may be an inflection point at which a prowlarr instance has so much data the backfill might time out. If this becomes a problem, we could add either a `--backfill` or `--disable-backfill` flag. This means that every time exportarr resets, the counters will also reset. This actually isn't too big an issues if we get there, prometheus aggregations understand how to handle counter resets when handling aggregations, it just means that lifetime queries may be much harder to query.

**Applicable issues**

- fixes #89 #35

**Additional information**

Example metric set:
```
# HELP prowlarr_history_total Total number of item in the history
# TYPE prowlarr_history_total gauge
prowlarr_history_total{url="https://prowlarr.cho.rtrox.com"} 169558
# HELP prowlarr_indexer_auth_queries_total Total number of auth queries
# TYPE prowlarr_indexer_auth_queries_total gauge
prowlarr_indexer_auth_queries_total{indexer="AnimeTosho (Usenet)",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_auth_queries_total{indexer="DOGnzb",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_auth_queries_total{indexer="DrunkenSlug",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_auth_queries_total{indexer="NZBCat",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_auth_queries_total{indexer="NZBgeek",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_auth_queries_total{indexer="Nzb.su",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_auth_queries_total{indexer="NzbPlanet",url="https://prowlarr.cho.rtrox.com"} 0
# HELP prowlarr_indexer_average_response_time_ms Average response time of indexers in ms
# TYPE prowlarr_indexer_average_response_time_ms gauge
prowlarr_indexer_average_response_time_ms{indexer="AnimeTosho (Usenet)",url="https://prowlarr.cho.rtrox.com"} 1864
prowlarr_indexer_average_response_time_ms{indexer="DOGnzb",url="https://prowlarr.cho.rtrox.com"} 4509
prowlarr_indexer_average_response_time_ms{indexer="DrunkenSlug",url="https://prowlarr.cho.rtrox.com"} 1366
prowlarr_indexer_average_response_time_ms{indexer="NZBCat",url="https://prowlarr.cho.rtrox.com"} 1119
prowlarr_indexer_average_response_time_ms{indexer="NZBgeek",url="https://prowlarr.cho.rtrox.com"} 1869
prowlarr_indexer_average_response_time_ms{indexer="Nzb.su",url="https://prowlarr.cho.rtrox.com"} 1693
prowlarr_indexer_average_response_time_ms{indexer="NzbPlanet",url="https://prowlarr.cho.rtrox.com"} 1147
# HELP prowlarr_indexer_enabled_total Total number of enabled indexers
# TYPE prowlarr_indexer_enabled_total gauge
prowlarr_indexer_enabled_total{url="https://prowlarr.cho.rtrox.com"} 7
# HELP prowlarr_indexer_failed_auth_queries_total Total number of failed auth queries
# TYPE prowlarr_indexer_failed_auth_queries_total gauge
prowlarr_indexer_failed_auth_queries_total{indexer="AnimeTosho (Usenet)",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_auth_queries_total{indexer="DOGnzb",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_auth_queries_total{indexer="DrunkenSlug",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_auth_queries_total{indexer="NZBCat",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_auth_queries_total{indexer="NZBgeek",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_auth_queries_total{indexer="Nzb.su",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_auth_queries_total{indexer="NzbPlanet",url="https://prowlarr.cho.rtrox.com"} 0
# HELP prowlarr_indexer_failed_grabs_total Total number of failed grabs
# TYPE prowlarr_indexer_failed_grabs_total gauge
prowlarr_indexer_failed_grabs_total{indexer="AnimeTosho (Usenet)",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_grabs_total{indexer="DOGnzb",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_grabs_total{indexer="DrunkenSlug",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_grabs_total{indexer="NZBCat",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_grabs_total{indexer="NZBgeek",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_grabs_total{indexer="Nzb.su",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_grabs_total{indexer="NzbPlanet",url="https://prowlarr.cho.rtrox.com"} 0
# HELP prowlarr_indexer_failed_queries_total Total number of failed queries
# TYPE prowlarr_indexer_failed_queries_total gauge
prowlarr_indexer_failed_queries_total{indexer="AnimeTosho (Usenet)",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_queries_total{indexer="DOGnzb",url="https://prowlarr.cho.rtrox.com"} 412
prowlarr_indexer_failed_queries_total{indexer="DrunkenSlug",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_queries_total{indexer="NZBCat",url="https://prowlarr.cho.rtrox.com"} 6
prowlarr_indexer_failed_queries_total{indexer="NZBgeek",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_queries_total{indexer="Nzb.su",url="https://prowlarr.cho.rtrox.com"} 12
prowlarr_indexer_failed_queries_total{indexer="NzbPlanet",url="https://prowlarr.cho.rtrox.com"} 0
# HELP prowlarr_indexer_failed_rss_queries_total Total number of failed rss queries
# TYPE prowlarr_indexer_failed_rss_queries_total gauge
prowlarr_indexer_failed_rss_queries_total{indexer="AnimeTosho (Usenet)",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_rss_queries_total{indexer="DOGnzb",url="https://prowlarr.cho.rtrox.com"} 617
prowlarr_indexer_failed_rss_queries_total{indexer="DrunkenSlug",url="https://prowlarr.cho.rtrox.com"} 1
prowlarr_indexer_failed_rss_queries_total{indexer="NZBCat",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_rss_queries_total{indexer="NZBgeek",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_rss_queries_total{indexer="Nzb.su",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_failed_rss_queries_total{indexer="NzbPlanet",url="https://prowlarr.cho.rtrox.com"} 0
# HELP prowlarr_indexer_grabs_total Total number of grabs
# TYPE prowlarr_indexer_grabs_total gauge
prowlarr_indexer_grabs_total{indexer="AnimeTosho (Usenet)",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_grabs_total{indexer="DOGnzb",url="https://prowlarr.cho.rtrox.com"} 490
prowlarr_indexer_grabs_total{indexer="DrunkenSlug",url="https://prowlarr.cho.rtrox.com"} 954
prowlarr_indexer_grabs_total{indexer="NZBCat",url="https://prowlarr.cho.rtrox.com"} 4
prowlarr_indexer_grabs_total{indexer="NZBgeek",url="https://prowlarr.cho.rtrox.com"} 1209
prowlarr_indexer_grabs_total{indexer="Nzb.su",url="https://prowlarr.cho.rtrox.com"} 636
prowlarr_indexer_grabs_total{indexer="NzbPlanet",url="https://prowlarr.cho.rtrox.com"} 309
# HELP prowlarr_indexer_queries_total Total number of queries
# TYPE prowlarr_indexer_queries_total gauge
prowlarr_indexer_queries_total{indexer="AnimeTosho (Usenet)",url="https://prowlarr.cho.rtrox.com"} 23
prowlarr_indexer_queries_total{indexer="DOGnzb",url="https://prowlarr.cho.rtrox.com"} 10683
prowlarr_indexer_queries_total{indexer="DrunkenSlug",url="https://prowlarr.cho.rtrox.com"} 16705
prowlarr_indexer_queries_total{indexer="NZBCat",url="https://prowlarr.cho.rtrox.com"} 12345
prowlarr_indexer_queries_total{indexer="NZBgeek",url="https://prowlarr.cho.rtrox.com"} 20323
prowlarr_indexer_queries_total{indexer="Nzb.su",url="https://prowlarr.cho.rtrox.com"} 10890
prowlarr_indexer_queries_total{indexer="NzbPlanet",url="https://prowlarr.cho.rtrox.com"} 15519
# HELP prowlarr_indexer_rss_queries_total Total number of rss queries
# TYPE prowlarr_indexer_rss_queries_total gauge
prowlarr_indexer_rss_queries_total{indexer="AnimeTosho (Usenet)",url="https://prowlarr.cho.rtrox.com"} 0
prowlarr_indexer_rss_queries_total{indexer="DOGnzb",url="https://prowlarr.cho.rtrox.com"} 13299
prowlarr_indexer_rss_queries_total{indexer="DrunkenSlug",url="https://prowlarr.cho.rtrox.com"} 13223
prowlarr_indexer_rss_queries_total{indexer="NZBCat",url="https://prowlarr.cho.rtrox.com"} 13158
prowlarr_indexer_rss_queries_total{indexer="NZBgeek",url="https://prowlarr.cho.rtrox.com"} 13282
prowlarr_indexer_rss_queries_total{indexer="Nzb.su",url="https://prowlarr.cho.rtrox.com"} 13187
prowlarr_indexer_rss_queries_total{indexer="NzbPlanet",url="https://prowlarr.cho.rtrox.com"} 13319
# HELP prowlarr_indexer_total Total number of configured indexers
# TYPE prowlarr_indexer_total gauge
prowlarr_indexer_total{url="https://prowlarr.cho.rtrox.com"} 7
# HELP prowlarr_indexer_vip_expires_in_seconds VIP expiration date
# TYPE prowlarr_indexer_vip_expires_in_seconds gauge
prowlarr_indexer_vip_expires_in_seconds{indexer="DOGnzb",url="https://prowlarr.cho.rtrox.com"} 5.2812141e+07
prowlarr_indexer_vip_expires_in_seconds{indexer="DrunkenSlug",url="https://prowlarr.cho.rtrox.com"} 3.3112941e+07
prowlarr_indexer_vip_expires_in_seconds{indexer="Nzb.su",url="https://prowlarr.cho.rtrox.com"} 8.8236141e+07
# HELP prowlarr_system_health_issues Total number of health issues by source, type, message and wikiurl
# TYPE prowlarr_system_health_issues gauge
prowlarr_system_health_issues{message="New update is available",source="UpdateCheck",type="warning",url="https://prowlarr.cho.rtrox.com",wikiurl="https://wiki.servarr.com/prowlarr/system#new-update-is-available"} 1
# HELP prowlarr_system_status System Status
# TYPE prowlarr_system_status gauge
prowlarr_system_status{url="https://prowlarr.cho.rtrox.com"} 1
# HELP prowlarr_user_agent_grabs_total Total number of grabs
# TYPE prowlarr_user_agent_grabs_total gauge
prowlarr_user_agent_grabs_total{url="https://prowlarr.cho.rtrox.com",user_agent="Other"} 142
prowlarr_user_agent_grabs_total{url="https://prowlarr.cho.rtrox.com",user_agent="Prowlarr"} 0
prowlarr_user_agent_grabs_total{url="https://prowlarr.cho.rtrox.com",user_agent="Radarr"} 54
prowlarr_user_agent_grabs_total{url="https://prowlarr.cho.rtrox.com",user_agent="Readarr"} 337
prowlarr_user_agent_grabs_total{url="https://prowlarr.cho.rtrox.com",user_agent="Sonarr"} 3069
# HELP prowlarr_user_agent_queries_total Total number of queries
# TYPE prowlarr_user_agent_queries_total gauge
prowlarr_user_agent_queries_total{url="https://prowlarr.cho.rtrox.com",user_agent="Other"} 0
prowlarr_user_agent_queries_total{url="https://prowlarr.cho.rtrox.com",user_agent="Prowlarr"} 161
prowlarr_user_agent_queries_total{url="https://prowlarr.cho.rtrox.com",user_agent="Radarr"} 10460
prowlarr_user_agent_queries_total{url="https://prowlarr.cho.rtrox.com",user_agent="Readarr"} 40258
prowlarr_user_agent_queries_total{url="https://prowlarr.cho.rtrox.com",user_agent="Sonarr"} 115077
# HELP prowlarr_user_agent_total Total number of active user agents
# TYPE prowlarr_user_agent_total gauge
prowlarr_user_agent_total{url="https://prowlarr.cho.rtrox.com"} 0
```

### CODE REVIEW

**Comment by onedr0p** [comment]
For the backfill issue there is the `ENABLE_ADDITIONAL_METRICS` setting you could use to enabling that. This option is generally associated with the other arrs for requests that take a long time to complete.

**Comment by rtrox** [comment]
@onedr0p - sure, sounds good. I just pushed a commit to do that. `ENABLE_ADDITIONAL_METRICS` enables backfill, leaving it unset disables backfill. I also added a note on the README to that effect.

**Comment by onedr0p** [comment]
Thanks I'll take a look soon. Hopefully I can test all these changes and the other PRs, and publish a release new version.

**Comment by rtrox** [comment]
Sounds good! Let me know if there's any changes you'd like to see or issues you find.

**Review by onedr0p — APPROVED** [review]

**Comment by Y0ngg4n** [comment]
@rtrox i don´t know why but my prowlarr exporter just exports this:
```
# HELP prowlarr_history_total Total number of item in the history
# TYPE prowlarr_history_total gauge
prowlarr_history_total{url="https://prowlarr.example.com:443"} 6.611552e+06
# HELP prowlarr_system_health_issues Total number of health issues by source, type, message and wikiurl
# TYPE prowlarr_system_health_issues gauge
prowlarr_system_health_issues{message="Applications unavailable due to failures for more than 6 hours: Whisparr",source="ApplicationLongTermStatusCheck",type="warning",url="https://prowlarr.example.com:443",wikiurl="https://wiki.servarr.com/prowlarr/system#applications-are-unavailable-due-to-failures"} 1
prowlarr_system_health_issues{message="Indexers unavailable due to failures: GloDLS",source="IndexerStatusCheck",type="warning",url="https://prowlarr.example.com:443",wikiurl="https://wiki.servarr.com/prowlarr/system#indexers-are-unavailable-due-to-failures"} 1
# HELP prowlarr_system_status System Status
# TYPE prowlarr_system_status gauge
prowlarr_system_status{url="https://prowlarr.example.com:443"} 1

```

**Comment by onedr0p** [comment]
Make sure your use the latest master tag until I publish a release.

**Comment by Y0ngg4n** [comment]
@onedr0p is already the latest master

**Comment by onedr0p** [comment]
Are you sure you pulled it again? The new digest on master is `sha256:4c5f522a55ca1ddf675d32aea7b37d3114e62c05bf45d4d92d3437ad75a07b40`

**Comment by Y0ngg4n** [comment]
@onedr0p 
weird
grafik

**Pull request merged**
