### PR TITLE
Automatically Update Image References when a new tag is released

### LINKED ISSUE #219: Latest Docker Image
Can we use the 1.5.5 tag? I noticed it was not updated in your docker compose example. It jumped from 1.5.3 to 1.5.5 and I was curious if there are any significant changes worth updating to that tag?

### PR DESCRIPTION
**Pull request by rtrox**
**Description of the change**

Adds a script & workflow which automatically updates image references to use the newly available tag.

I used regex rather than a yaml parser here, as the yaml parser wipes out comments and key ordering, which makes the examples much more difficult to follow. The workflow tests prior to committing to ensure that the bot has only changed `yaml` files inside the `examples` dir, or `md` files anywhere.

This PR also updates all the image versions to the latest `v1.5.5`, as this workflow will only be triggered for the first time on the next release.

**Benefits**

Ensures that image tags in examples and READMEs are always up to date.

**Possible drawbacks**

None. If for some reason the commit fails, it will not block the release.

**Applicable issues**

- fixes #219 

**Additional information**

An example workflow run can be seen working here:
image
https://github.com/rtrox/exportarr/actions/runs/6444162502

(Used fake new tags to trigger the workflow on my fork)

### CODE REVIEW

**Comment by phyzical** [comment]
@rtrox i wonder if we shouldn't just leverage renovate for this?

i can take a crack next week if you want to give it a go

**Comment by rtrox** [comment]
@phyzical I've done it in other repos, and I'm honestly not a huge fan of using renovate for documentation updates. for a couple reasons:
1. It's a much longer round trip. Renovate operates on a cadence, and on that set cadence has to look at all of our available dependencies at their sources, determine if the version at that source is newer than is already present, and cut a PR to automerge.  That long round trip can lead to a substantial time gap between a new version landing, and the docs being update.
2. Counting on renovate for this creates a semi-opaque dependency on the repo-wide renovate config, which can lead to inadvertant issues in the future (for example, if 6 months from now, we want to rate limit dependency PRs, or other repo-wide changes, it will impact documentation updates in a way that isn't immediately clear from the PR, especially for someone who has forgotten how the docs get updated, or never knew in the first place).
3. It's confined to dependency updates. The approach in this PR gives us a spot to add other rendering steps if needed in the future (for example, updating the list of available apps or config values automatically).

These are all minor, so if there's a compelling reason to use renovate I haven't thought of, glad for us to consider that approach.

**Comment by onedr0p** [comment]
I feel indifferent about automating this, on one hand it's nice for people to simply copy and paste on the other hand it's maintenance burden on our end to keep this working. What I mean is if https://github.com/onedr0p/exportarr/issues/184 ever happens we would need to update the script to remove the Kubernetes manifests from being changed via this script. There's also the problem that comes up when we create a new release but the tag doesn't have the updated manifests because it only gets pushed to `master` after release.

I would rather rely on documentation and move the compose example to the README for people to review but I am open to more discussion around all this. Maybe we can just have the examples use `v1` tag instead of the full semver tag?

**Comment by rtrox** [comment]
Ah, yea, #184 is a good call! I'll go ahead and close this out.

using the `v1` tag makes sense, I was trying to avoid `latest` to promote good practices, but `v1` at least is only tied to tagged releases.

**Pull request closed without merging**
