### PR TITLE
(3/3) Use Zap for structured logging rather than logrus.

### LINKED ISSUE #57: Refactor: Switch to zap logging library
# Details

**Describe the solution you'd like:**

logrus is currently in maintenance mode, and zap looks to be a good replacement.

### PR DESCRIPTION
**Pull request by rtrox**
**NOTE: this is not actually a particularly large PR, but it depends on ~~#110  and~~ #113. This will be easiest to review after reviewing & merging those PRs, and rebasing this one. In the meantime, you can see just the changes in this PR by viewing [this commit](https://github.com/onedr0p/exportarr/commit/d011cf60b01182ab6484b82624fdee84c5d79831).**

**Description of the change**

Per title, replaces Logrus with Zap, and utilizes structured logging for logs. This PR also adds a new flag, `--log-format`, which allows toggling between Console & JSON logging. Examples of what logging looks like with each:

```bash
# --log-format console (default) --log-level debug
2023-03-17T10:54:23.700-0700	DEBUG	Logger initialized
2023-03-17T10:54:23.701-0700	INFO	Starting HTTP Server	{"interface": "0.0.0.0", "port": 8081}
2023-03-17T10:54:28.453-0700	DEBUG	Request Received	{"remote_addr": "[::1]:61839", "method": "GET", "url": "/metrics"}
2023-03-17T10:54:28.454-0700	INFO	Sending HTTP request	{"url": "https://radarr.redact.com/api/v3/rootfolder"}
2023-03-17T10:54:28.454-0700	INFO	Sending HTTP request	{"url": "https://radarr.redact.com/api/v3/history"}
2023-03-17T10:54:28.454-0700	INFO	Sending HTTP request	{"url": "https://radarr.redact.com/api/v3/system/status"}
2023-03-17T10:54:28.454-0700	INFO	Sending HTTP request	{"url": "https://radarr.redact.com/api/v3/queue"}
2023-03-17T10:54:28.455-0700	INFO	Sending HTTP request	{"url": "https://radarr.redact.com/api/v3/health"}
2023-03-17T10:54:28.455-0700	INFO	Sending HTTP request	{"url": "https://radarr.redact.com/api/v3/movie"}
2023-03-17T10:54:28.640-0700	DEBUG	Request Received	{"remote_addr": "[::1]:61839", "method": "GET", "url": "/favicon.ico"}
2023-03-17T10:55:27.465-0700	INFO	Shutting down due to signal: interrupt
```

```json5
# --log-format json --log-format debug
{"level":"debug","ts":1679075648.1925929,"msg":"Logger initialized"}
{"level":"info","ts":1679075648.192713,"msg":"Starting HTTP Server","interface":"0.0.0.0","port":8081}
{"level":"debug","ts":1679075652.173582,"msg":"Request Received","remote_addr":"[::1]:61825","method":"GET","url":"/metrics"}
{"level":"info","ts":1679075652.173814,"msg":"Sending HTTP request","url":"https://radarr.redact.com/api/v3/history"}
{"level":"info","ts":1679075652.173852,"msg":"Sending HTTP request","url":"https://radarr.redact.com/api/v3/rootfolder"}
{"level":"info","ts":1679075652.173957,"msg":"Sending HTTP request","url":"https://radarr.redact.com/api/v3/health"}
{"level":"info","ts":1679075652.173992,"msg":"Sending HTTP request","url":"https://radarr.redact.com/api/v3/system/status"}
{"level":"info","ts":1679075652.174219,"msg":"Sending HTTP request","url":"https://radarr.redact.com/api/v3/movie"}
{"level":"info","ts":1679075652.175252,"msg":"Sending HTTP request","url":"https://radarr.redact.com/api/v3/queue"}
{"level":"debug","ts":1679075652.382421,"msg":"Request Received","remote_addr":"[::1]:61825","method":"GET","url":"/favicon.ico"}
{"level":"info","ts":1679075660.293376,"msg":"Shutting down due to signal: interrupt"}
```

**Benefits**

- **Maintenance** - Logrus has entered maintenance mode, Zap is under active development
- **Parseability** - Structured logging, especially with a JSON formatter, is significantly easier to parse using log aggregation tools like loki, logstash, or splunk.

**Possible drawbacks**

Using a new logger comes with a change in logging format.

**Applicable issues**

- fixes #57 

**Additional information**

### CODE REVIEW

**Comment by rtrox** [comment]
Good to go here, too -- validation errors were trying to log before the logger had been configured. Since these need to immediately exit, printing the error directly to stderr.

**Comment by onedr0p** [comment]
I've reviewed this commit so anytime you're free to rebase we can merge it.

**Comment by rtrox** [comment]
rebased, we should be all set!

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
I'm going to test out the changes further today and release v2.0.0 soon.

**Pull request merged**
