### PR TITLE
Update k8s docs

### PR DESCRIPTION
**Pull request by 0xEmma**
**Description of the change**

Updates the kubernetes docs to be workable
- Updates the docker image version from 1.0.0 to 1.5.0
- Creates the monitoring within a single deployment/pod, containing all the containers
- has an example secret file, which was missing prior
- uses prom annontations instead of core-os monitoring

**Benefits**
- Easier to deploy / More up to date example

**Possible drawbacks**
N/A

**Applicable issues**

N/A

**Additional information**

### CODE REVIEW

**Comment by rtrox** [comment]
@0xEmma  - Thanks for the PR! I think adding the scrape annotation makes sense, but can we leave the `ServiceMonitor` in the example? Not all folks have annotations enabled. `prometheus-operator` consumes `ServiceMonitor` objects, btw -- it's another instance where the `apiVersion` is a relic of the company that originally created it, but it's not a CoreOS specific resource (`coreos.com` is no longer a company as such, it was acquired by Fedora).

Otherwise, Igtm! I think longer term we should add a manifest example for including exportarr as a container in the *arr deployment, too, as I think this is a common pattern (that's the pattern being discussed in #133 for a helm chart, too) -- I can create an issue for that.

**Comment by onedr0p** [comment]
IIRC scrape annotations are also being deprecated by prometheus-operator, they are looking to remove them sometime in the future.

**Comment by rtrox** [comment]
Ah, if that's the case, we should follow best practices -- let's stick with `ServiceMonitor` and leave off the annotations.

**Comment by onedr0p** [comment]
I think it might be better to supply a helm chart and package it as an oci artifact people can use. I would like to defer that until the common library rewrite is completed though.

https://github.com/bjw-s/helm-charts/pull/148

**Comment by onedr0p** [comment]
@0xEmma thanks for the contribution here but I think we can collapse this into a single issue. If you wanted to support a kustomization install of the exporter I would be open to that idea as well but just having manifests is not very helpful from a UX point of view. It would be nice to give people the ability to deploy this with either helm, kustomize or both :)

Closing in favor of https://github.com/onedr0p/exportarr/issues/183

**Pull request closed without merging**
