### PR TITLE
chore: Use composite actions for workflows

### PR DESCRIPTION
**Pull request by onedr0p**
I think it might be a good idea to use composite actions, this should allow up to move the workflow actions outside of the workflow folder. I need to step away for a bit but I'll get back to hacking at this soon.

### CODE REVIEW

**Comment by onedr0p** [comment]
@rtrox I believe this should to be good to look over now.

**Comment by rtrox** [comment]
Ah nice! Thanks @onedr0p!

**Comment by onedr0p** [comment]
Eek https://github.com/onedr0p/exportarr/actions/runs/5230480308/jobs/9444049812

**Comment by rtrox** [comment]
Oh, I see -- since these are all running on the same runner, now, `go-tests` is polluting the builds (it's running a `go mod tidy`, and then the tests output a coverage profile). We could probably try to make `go-tests` idempotent, but I think it might be better just to pull it out as it's own job so we always start the releases from a fresh checkout.

If you want to go the idempotent route, we can fail fast on go mod tidy like this:
```
      - name: Tidy
        run: |
          go version
          go mod tidy
          git diff --exit-code
```

And we can probably just remove the coverage profile since we're not using coveralls or codecov right now

**Comment by onedr0p** [comment]
Either way works for me, feel free to open a PR or I can try to get to it later today.

**Pull request merged**
