### PR TITLE
(2/3) Use Cobra, Koanf, and Ozzo rather than urfave/cli

### LINKED ISSUE #58: Refactor: Switch to koanf & cobra for config & CLI library
# Details

**Describe the solution you'd like:**

https://github.com/knadh/koanf

### PR DESCRIPTION
**Pull request by rtrox**
**This PR depends on #110 -- please review and merge first, and I will rebase this PR**

**Description of the change**

Sorry, I know this is a huge PR! It would have been way more work to try and move to Cobra and Koanf separately. This PR attempts to make no functional changes, and only refactor to new libraries. The libraries in question:
- Cobra (CLI)
- Koanf (Configuration)
- Ozzo (Validation)

Of course, I failed slightly at this -- I added Signal handling to the HTTP Server to shutdown gracefully when stopped.

**Benefits**

- **Better Separation of Concerns** - config logic now all happens in `config`, config logic has been removed from `client`.
- **Simplified Command Flow** - Each Command now only specifies the collectors which should run
- **New Libraries** - closes #58 
- **Stronger Validation** - ozzo provides well formed validation rules, to test for valid IPs, URLs, regex, etc with a simpler interface.

**Possible drawbacks**

It's just a big PR :-(

**Applicable issues**

- fixes #58

**Additional information**

### CODE REVIEW

**Comment by onedr0p** [comment]
You are a machine! I am giving this a solid look thru but overall looks very solid!

**Comment by onedr0p** [comment]
My only concern is with using ozzo is it's current maintained state.

https://github.com/go-ozzo/ozzo-validation/issues/162

**Comment by rtrox** [comment]
oof, good catch! I totally missed that >.< I've been using it in other projects, looks like I have some updating to do :-D 

Bummer that it's no longer maintained, it had a super clean interface. It looks like some folks are [trying to revive it in a fork](https://github.com/go-ozzo/ozzo-validation/issues/181), but it was announced 3 weeks ago, which is coincidentally also it's last commit. Probably want to let that one bake a bit before counting on it.

I'll take a look at the interfaces of the libraries you linked and work on updating this.

**Comment by rtrox** [comment]
I just updated this to 1) rebase, and 2) move to gookit/validate rather than ozzo.

**Comment by rtrox** [comment]
hold off one sec -- found a bug with how validations are reported

**Comment by rtrox** [comment]
whoops -- wrong PR. This one is good to go.

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
I spent some time reviewing the branch this morning and I'm very impressed!

**Pull request merged**
